trainer:
  max_epochs: 400
  log_every_n_steps: 10
  accelerator: cuda
  default_root_dir: ~/working/models/unet_cvnxt_sm-ltfl-sta-ep400-longcat
  devices: [0]
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        save_top_k: 1
        save_last: true
        filename: '{epoch}-{val_loss:.2f}'
model:
  class_path: ftw_ma.trainers.CustomSemanticSegmentationTask
  init_args:
    class_weights: null
    loss: localtversky
    model: unet
    backbone: tu-convnext_small.fb_in22k
    weights: true
    patch_weights: false
    in_channels: 4
    num_classes: 3
    ignore_index: 3
    lr: 1e-3
    patience: 400
data:
  class_path: ftw_ma.datamodule.FTWMapAfricaDataModule
  init_args:
    temporal_options: windowB
    batch_size: 32
    num_workers: 8
    num_samples: -1
    data_dir: /home/airg/data/labels/cropland/
    catalog: ~/projects/ftw-mappingafrica-integration/data/ftw-catalog-long2.csv
    normalization_strategy: min_max
    normalization_stat_procedure: gab
    global_stats:
      mean: null
      std: null
      min: [68.438525]
      max: [5772.288821]
    img_clip_val: 0
    aug_list: [rotation, hflip, vflip, sharpness, rescale, brightness]
seed_everything: 7
